SET PAGES 200 LIN 200
BREAK ON DISKGROUP SKIP PAGE
COMPUTE SUM OF TOTAL_GB ON DISKGROUP
COMPUTE SUM OF FREE_GB ON DISKGROUP
COMPUTE SUM OF OS_GB ON DISKGROUP
--COMPUTE COUNT OF PATH ON DISKGROUP
COL DISKGROUP FORMAT A25
COL DISKS FORMAT A35
COL PATH FORMAT A35
COL NAME FORMAT A30
COL HEADER_STATUS FORMAT A20
COL TOTAL_GB FORMAT 99999990.99
COL FREE_GB FORMAT 99999990.99
COL OS_GB FORMAT 99999990.99
COL PCT_FREE FORMAT 990.99
SELECT 
	NVL(A.NAME,'(FREE)') 
	|| ' ('||substr(type,1,1)||','||NVL(ALLOCATION_UNIT_SIZE/1024/1024,0)||'M,'||NVL(BLOCK_SIZE/1024,0)||'K)'  DISKGROUP, 
	B.PATH PATH, 
	B.NAME,
	B.MOUNT_STATUS,
	B.HEADER_STATUS, 
	B.FAILGROUP,
	--B.FAILGROUP_TYPE,
	--B.VOTING_FILE,
        B.OS_MB/1024 OS_GB,
	B.TOTAL_MB/1024 TOTAL_GB, 
	B.FREE_MB/1024 FREE_GB, 
	(B.FREE_MB/replace(B.TOTAL_MB,0,1))*100 PCT_FREE
FROM V$ASM_DISKGROUP A, V$ASM_DISK B
WHERE A.GROUP_NUMBER(+)=B.GROUP_NUMBER
ORDER BY A.NAME, B.NAME, B.PATH
;
