SET LIN 200 PAGES 200 VERIFY OFF
COL BEGIN_INTERVAL_TIME FORMAT A30
COL END_INTERVAL_TIME FORMAT A30
SELECT 
	SNAP_ID,
	DBID,
	INSTANCE_NUMBER,
	BEGIN_INTERVAL_TIME,
	END_INTERVAL_TIME
FROM DBA_HIST_SNAPSHOT
WHERE BEGIN_INTERVAL_TIME > SYSDATE - 1
ORDER BY SNAP_ID
;

SELECT * from table(DBMS_WORKLOAD_REPOSITORY.AWR_REPORT_TEXT(&dbid,&inst_num,&begin_snap,&end_snap,8));

/* MAYBE I'LL FIGURE OUT HOW TO DO THIS IN A PL/SQL BLOCK ONE DAY
VARIABLE REPORT CLOB;
DECLARE
	v_dbid number;
	v_inst_num number;
	v_report CLOB;
BEGIN
	SELECT DBID INTO v_dbid FROM V$DATABASE;
	SELECT INSTANCE_NUMBER INTO v_inst_num FROM V$INSTANCE;

	:REPORT := 
		SELECT * FROM TABLE (
			DBMS_WORKLOAD_REPOSITORY.AWR_REPORT_TEXT(
			   l_dbid       => v_dbid,
			   l_inst_num   => v_inst_num,
			   l_bid        => 16075,
			   l_eid        => 16076,
			   l_options    => 8
			)
		);
END;
/
*/
