set lin 400 pages 400
col BEGIN_INTERVAL_TIME format a30
col CPU_SPE		format 9999990.99
col ELAPSED_SPE	format 9999990.99
col IOWAIT_SPE	format 9999990.99
col CLWAIT_SPE	format 9999990.99
col APWAIT_SPE	format 9999990.99
col CCWAIT_SPE	format 9999990.99
col READS_PS	format 9999990.99
col READMB_PE	format 9999990.99
col READS_PE	format 9999990.99
col READREQ_PE	format 9999990.99
col BPR			format 9999990.99
col GETS_PE		format 9999990.99
col FORCE_MATCHING_SIGNATURE format 999999999999999999999
col PARSING_SCHEMA_NAME format a10
col exe_total format 999999
col px_exe_total format 999
SELECT 
--	 B.SNAP_ID
--	,B.INSTANCE_NUMBER
	 B.BEGIN_INTERVAL_TIME
	,A.PARSING_SCHEMA_NAME
	,A.SQL_ID 
	,A.PLAN_HASH_VALUE
	,A.OPTIMIZER_COST
	,A.EXECUTIONS_DELTA EXECUTIONS  
	,A.FETCHES_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1) FETCHES_PE        
	,A.SORTS_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1) SORTS_PE
	,A.END_OF_FETCH_COUNT_DELTA EOFCD
	,A.PX_SERVERS_EXECS_DELTA
	,A.DISK_READS_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1) READS_PE
	,A.PHYSICAL_READ_REQUESTS_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1) READREQ_PE
	,(A.DISK_READS_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1))/REPLACE((A.PHYSICAL_READ_REQUESTS_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1)),0,1) BPR
	,(PHYSICAL_READ_BYTES_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1))/1024/1024 READMB_PE
	,A.BUFFER_GETS_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1) GETS_PE
	,A.ROWS_PROCESSED_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1) ROWS_PE
	,(A.ELAPSED_TIME_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1))/1000000 ELAPSED_SPE
	,(A.CPU_TIME_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1))/1000000 CPU_SPE
	,(A.IOWAIT_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1))/1000000 IOWAIT_SPE
	,(A.CLWAIT_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1))/1000000 CLWAIT_SPE
	,(A.APWAIT_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1))/1000000 APWAIT_SPE
	,(A.CCWAIT_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1))/1000000 CCWAIT_SPE
	,(A.DISK_READS_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1))/REPLACE(((A.IOWAIT_DELTA/REPLACE(A.EXECUTIONS_DELTA,0,1))/1000000),0,1) READS_PS
--	,A.FORCE_MATCHING_SIGNATURE
FROM 
	DBA_HIST_SQLSTAT A,
	DBA_HIST_SNAPSHOT B
WHERE
		A.SNAP_ID=B.SNAP_ID
	AND A.DBID=B.DBID 
	AND A.INSTANCE_NUMBER=B.INSTANCE_NUMBER 
--	AND PARSING_SCHEMA_NAME='HYBRIS'
--	AND B.SNAP_ID BETWEEN 2079 and 2080
	AND (A.SQL_ID IN ('2s522n1fyabsk'))
--	AND (A.SQL_ID IN ('6tnwbqdqf6v3t','bwf0zsjpysjbw','gdj7j8qfrsahm','fy3xg2dd4shb8')) -- Sydney's 
--	AND END_OF_FETCH_COUNT_TOTAL !=0
--	AND B.BEGIN_INTERVAL_TIME > SYSDATE-2
ORDER BY 
	B.END_INTERVAL_TIME
;


SELECT 
	SQL_ID, 
	SQL_OPNAME,
	(MAX(SQL_EXEC_ID)-MIN(SQL_EXEC_ID))+1 EXECUTIONS, 
	COUNT(SID_SER) SESSIONS,
	SUM(PX_SESSIONS) PX_SESSIONS,
	SUM(EXTRACT(HOUR FROM DURATION)*60*60 + EXTRACT(MINUTE FROM DURATION)*60 + EXTRACT(SECOND FROM DURATION)) ELAPSED_S,
	--(MAX(SQL_EXEC_END) - MIN(SQL_EXEC_START))*24*60*60 DURATION_S,
	(SUM(EXTRACT(HOUR FROM DURATION)*60*60 + EXTRACT(MINUTE FROM DURATION)*60 + EXTRACT(SECOND FROM DURATION))) / ((MAX(SQL_EXEC_ID)-MIN(SQL_EXEC_ID))+1)  ELAPSED_SPE,
	MIN(SQL_EXEC_START) MIN_EXEC_START,
	MAX(SQL_EXEC_END) MAX_EXEC_END
FROM (
		SELECT
			 TO_CHAR(DECODE(A.QC_SESSION_ID,NULL,A.SESSION_ID,A.QC_SESSION_ID) ||','|| DECODE(A.QC_SESSION_SERIAL#,NULL,A.SESSION_SERIAL#,A.QC_SESSION_SERIAL#)) "SID_SER"
			,SUM(DECODE(A.QC_SESSION_ID,NULL,0,1)) PX_SESSIONS
			,A.SQL_ID
			,A.SQL_OPNAME
			,A.SQL_EXEC_ID
			,A.SQL_EXEC_START
			,CAST(MAX(A.SAMPLE_TIME) AS DATE) "SQL_EXEC_END"
			,MAX(A.SAMPLE_TIME) - SQL_EXEC_START "DURATION" 
		FROM 
			DBA_HIST_ACTIVE_SESS_HISTORY A,
			--V$ACTIVE_SESSION_HISTORY A,
			DBA_USERS B
		WHERE 
				A.USER_ID = B.USER_ID
--			AND B.USERNAME = 'DCDS_ETL'
			--AND A.SAMPLE_TIME >= SYSDATE - 1
			--AND A.SAMPLE_TIME BETWEEN TO_TIMESTAMP('2014-03-06 00:00:00','YYYY-MM-DD HH24:MI:SS') AND TO_TIMESTAMP('2014-03-07 00:00:00','YYYY-MM-DD HH24:MI:SS')
			AND A.SQL_EXEC_ID IS NOT NULL
			--AND A.SQL_OPNAME NOT IN ('INSERT','UPDATE')
			AND SQL_ID='53jj9r8qwm3jt'
			--AND ((A.SESSION_ID = 1896 AND A.SESSION_SERIAL#=17397) OR (A.QC_SESSION_ID = 1896 AND A.QC_SESSION_SERIAL#=17397))
		GROUP BY
			 TO_CHAR(DECODE(A.QC_SESSION_ID,NULL,A.SESSION_ID,A.QC_SESSION_ID) ||','|| DECODE(A.QC_SESSION_SERIAL#,NULL,A.SESSION_SERIAL#,A.QC_SESSION_SERIAL#))
			,A.SQL_ID
			,A.SQL_OPNAME
			,A.SQL_EXEC_ID
			,A.SQL_EXEC_START 
;



set lin 400 pages 400
col BEGIN_INTERVAL_TIME format a30
col CPU_MPE		format 999990.999
col ELAPSED_MPE	format 999990.999
col IOWAIT_MPE	format 999990.999
col CLWAIT_MPE	format 999990.999
col APWAIT_MPE	format 999990.999
col CCWAIT_MPE	format 999990.999
col READS_PS	format 999990.999
col READMB_PE	format 999990.999
col FORCE_MATCHING_SIGNATURE format 999999999999999999999
col PARSING_SCHEMA_NAME format a10
col exe_total format 999999
col px_exe_total format 999
SELECT 
	 TO_CHAR(B.BEGIN_INTERVAL_TIME,'YYYY-MM-DD') "DATE"
	,A.PARSING_SCHEMA_NAME
	,A.SQL_ID 
	,A.PLAN_HASH_VALUE
	--,MAX(A.PX_SERVERS_EXECS_DELTA)
	,SUM(A.FETCHES_DELTA)/REPLACE(SUM(EXECUTIONS_DELTA),0,1) FETCHES_PE        
	,SUM(A.SORTS_DELTA)/REPLACE(SUM(EXECUTIONS_DELTA),0,1) SORTS_PE
	,SUM(A.DISK_READS_DELTA)/REPLACE(SUM(EXECUTIONS_DELTA),0,1) READS_PE
	,SUM(A.PHYSICAL_READ_REQUESTS_DELTA)/REPLACE(SUM(EXECUTIONS_DELTA),0,1) READREQ_PE
	,(SUM(PHYSICAL_READ_BYTES_DELTA)/REPLACE(SUM(EXECUTIONS_DELTA),0,1))/1024/1024 READMB_PE
	,SUM(A.BUFFER_GETS_DELTA)/REPLACE(SUM(EXECUTIONS_DELTA),0,1) GETS_PE
	,SUM(A.ROWS_PROCESSED_DELTA)/REPLACE(SUM(EXECUTIONS_DELTA),0,1) ROWS_PE
	,(((SUM(A.ELAPSED_TIME_DELTA)/REPLACE(SUM(EXECUTIONS_DELTA),0,1))/1000000)/60) ELAPSED_MPE
	,((SUM(A.CPU_TIME_DELTA)/REPLACE(SUM(EXECUTIONS_DELTA),0,1))/1000000)/60 CPU_MPE
	,((SUM(A.IOWAIT_DELTA)/REPLACE(SUM(EXECUTIONS_DELTA),0,1))/1000000)/60 IOWAIT_MPE
	,((SUM(A.CLWAIT_DELTA)/REPLACE(SUM(EXECUTIONS_DELTA),0,1))/1000000)/60 CLWAIT_MPE
	,((SUM(A.APWAIT_DELTA)/REPLACE(SUM(EXECUTIONS_DELTA),0,1))/1000000)/60 APWAIT_MPE
	,((SUM(A.CCWAIT_DELTA)/REPLACE(SUM(EXECUTIONS_DELTA),0,1))/1000000)/60 CCWAIT_MPE
FROM 
	DBA_HIST_SQLSTAT A,
	DBA_HIST_SNAPSHOT B
WHERE
		A.SNAP_ID=B.SNAP_ID
	AND A.DBID=B.DBID 
	AND A.INSTANCE_NUMBER=B.INSTANCE_NUMBER 
--	AND PARSING_SCHEMA_NAME='HYBRIS'
--	AND B.SNAP_ID BETWEEN 2079 and 2080
	AND (A.SQL_ID IN ('956978fcf5jj6','4ma3u76n0t501','fy6pd1ktmv4bj'))
--	AND END_OF_FETCH_COUNT_TOTAL !=0
GROUP BY
	 TO_CHAR(B.BEGIN_INTERVAL_TIME,'YYYY-MM-DD')
	,A.PARSING_SCHEMA_NAME
	,A.SQL_ID
	,A.PLAN_HASH_VALUE
ORDER BY 
	A.SQL_ID, "DATE"
;


alter session set nls_date_format='YYYY-MM-DD HH24:MI:SS';
select 
	INSTANCE_NUMBER, 
	SQL_ID,
--	QC_INSTANCE_ID, 
--	QC_SESSION_ID, 
--	QC_SESSION_SERIAL#, 
	USER_ID, 
--	SQL_EXEC_ID,
	SQL_EXEC_START "START", 
	max(sample_time) "END", 
	max(sample_time)-SQL_EXEC_START "DURATION" 
from 
	dba_hist_active_sess_history 
where 
	--sql_id in (select sql_id from DBA_HIST_SQLTEXT where SQL_TEXT LIKE '%GROUP BY pad.AS_OF_BUSINESS_DATE%')
	sql_id = '4ma3u76n0t501'
group by 
	INSTANCE_NUMBER, 
	SQL_ID,
	QC_INSTANCE_ID, 
	QC_SESSION_ID, 
	QC_SESSION_SERIAL#, 
	USER_ID, 
	SQL_EXEC_ID,
	SQL_EXEC_START
order by "START";




col "Elapsed (s)"	format 99999990.99
col "CPU (s)"		format 99999990.9999
col "IOWait (s)"	format 99999990.99
col "Gets/Execs" 	format 99999990.99
col "Ela(s)/Execs"	format 99999990.9999
col "Rows/Execs"	format 99999990.99
col "Reads"			format 99999999
col "Sorts"			format 99999999
col "Fetches"		format 99999999
col "Reads/Execs"	format 99999990.99
col "Fetches/Execs"	format 99999990.99
col "Sorts/Execs"	format 99999990.99
col operation		format a15
col options			format a10
col object_owner	format a10

SELECT
	A.SQL_ID,
	A.PLAN_HASH_VALUE,
	SUM(A.EXECUTIONS_DELTA) "Execs",
	SUM(A.BUFFER_GETS_DELTA) "Gets",
	SUM(A.FETCHES_DELTA) "Fetches",
	SUM(A.DISK_READS_DELTA) "Reads",
	SUM(A.SORTS_DELTA) "Sorts",
	SUM(A.ROWS_PROCESSED_DELTA) "Rows",
	SUM(A.ELAPSED_TIME_DELTA/1000000) "Elapsed (s)",
	SUM(A.CPU_TIME_DELTA/1000000) "CPU (s)",
	SUM(A.IOWAIT_DELTA/1000000) "IOWait (s)",
	SUM(A.BUFFER_GETS_DELTA)/REPLACE(SUM(A.EXECUTIONS_DELTA),0,1) "Gets/Execs",
	SUM(A.FETCHES_DELTA)/REPLACE(SUM(A.EXECUTIONS_DELTA),0,1) "Fetches/Execs",
	SUM(A.DISK_READS_DELTA)/REPLACE(SUM(A.EXECUTIONS_DELTA),0,1) "Reads/Execs",
	SUM(A.SORTS_DELTA)/REPLACE(SUM(A.EXECUTIONS_DELTA),0,1) "Sorts/Execs",
	SUM(A.ROWS_PROCESSED_DELTA)/REPLACE(SUM(A.EXECUTIONS_DELTA),0,1) "Rows/Execs",
	SUM(A.ELAPSED_TIME_DELTA)/REPLACE(SUM(A.EXECUTIONS_DELTA),0,1)/1000000 "Ela(s)/Execs"
FROM
	DBA_HIST_SQLSTAT A, 
	DBA_HIST_SNAPSHOT B
WHERE 
		A.SNAP_ID=B.SNAP_ID 
	AND A.INSTANCE_NUMBER = B.INSTANCE_NUMBER
	AND A.PARSING_SCHEMA_NAME = 'HYBRIS'
	AND B.SNAP_ID BETWEEN 2079 AND 2080
--	AND B.BEGIN_INTERVAL_TIME BETWEEN TO_TIMESTAMP('2013-12-19 00:00:00','YYYY-MM-DD HH24:MI:SS') AND TO_TIMESTAMP('2013-12-20 00:00:00','YYYY-MM-DD HH24:MI:SS')
--	AND A.SQL_ID = '431skfbhk92q2'
GROUP BY
	A.SQL_ID,
	A.PLAN_HASH_VALUE
ORDER BY 
--	"Execs"
	"Gets/Execs"
;





SELECT
	A.SQL_ID,
	A.PLAN_HASH_VALUE,
	C.OPERATION,
	C.OPTIONS,
	C.OBJECT_OWNER,
	C.OBJECT_NAME,
	SUM(A.EXECUTIONS_DELTA) "Execs",
	SUM(A.BUFFER_GETS_DELTA) "Gets",
	SUM(A.ROWS_PROCESSED_DELTA) "Rows",
	SUM(A.ELAPSED_TIME_DELTA/1000000) "Elapsed (s)",
	SUM(A.CPU_TIME_DELTA/1000000) "CPU (s)",
	SUM(A.IOWAIT_DELTA/1000000) "IOWait (s)",
	SUM(A.ROWS_PROCESSED_DELTA)/REPLACE(SUM(A.EXECUTIONS_DELTA),0,1) "Rows/Execs",
	SUM(A.BUFFER_GETS_DELTA)/REPLACE(SUM(A.EXECUTIONS_DELTA),0,1) "Gets/Execs",
	SUM(A.ELAPSED_TIME_DELTA)/REPLACE(SUM(A.EXECUTIONS_DELTA),0,1)/1000000 "Ela(s)/Execs"
FROM
	DBA_HIST_SQLSTAT A, 
	DBA_HIST_SNAPSHOT B,
	DBA_HIST_SQL_PLAN C
WHERE 
		A.SNAP_ID=B.SNAP_ID 
	AND A.INSTANCE_NUMBER = B.INSTANCE_NUMBER
	AND A.SQL_ID = C.SQL_ID
	AND A.PLAN_HASH_VALUE = C.PLAN_HASH_VALUE
	AND C.OPTIONS = 'FULL'
	AND A.PARSING_SCHEMA_NAME = 'HYBRIS'
	AND B.SNAP_ID BETWEEN 2079 AND 2080
GROUP BY
	A.SQL_ID,
	A.PLAN_HASH_VALUE,
	C.OPERATION,
	C.OPTIONS,
	C.OBJECT_OWNER,
	C.OBJECT_NAME
ORDER BY
	A.SQL_ID
;









select sql_id, child_number, plan_hash_value, executions, (ELAPSED_TIME/executions)/1000000 secs_per_exec
from v$sql where sql_id='dvba4rwpkw9n6';