SELECT 
	COUNT(*)
	,A.SQL_ID 
	,B.PARSING_SCHEMA_NAME
--	,A.SQL_TEXT
FROM 
	DBA_HIST_SQLTEXT A,
	DBA_HIST_SQLSTAT B
WHERE 
		A.SQL_ID = B.SQL_ID
	AND A.COMMAND_TYPE=3
	AND	A.SQL_TEXT LIKE '%select distinct acf_plan_code, acf_account_number from DCDWACF.ACF_2502_FUND_VALUE) and fund_value =0)) T1,%' 
GROUP BY 
	 A.SQL_ID
	,B.PARSING_SCHEMA_NAME
--	,A.SQL_TEXT
;


set long 999999 longc 160 lin 400 pages 10000
break on report skip page
SELECT 
	C.CNT,
	C.SQL_ID,
	C.PARSING_SCHEMA_NAME,
	D.SQL_TEXT
FROM
	(
		SELECT 
			COUNT(*) CNT, A.SQL_ID, B.PARSING_SCHEMA_NAME
		FROM 
			DBA_HIST_SQLTEXT A,	DBA_HIST_SQLSTAT B
		WHERE 
			A.SQL_ID = B.SQL_ID
			--AND A.COMMAND_TYPE=3
			AND	A.SQL_TEXT LIKE '%/*YANTRA*/%FROM_ZIP%' 
		GROUP BY A.SQL_ID, B.PARSING_SCHEMA_NAME
	) C,
	DBA_HIST_SQLTEXT D
WHERE 
	C.SQL_ID = D.SQL_ID
;
	
	
	

SELECT 
	COUNT(*)
	,A.SQL_ID 
	,B.PARSING_SCHEMA_NAME
--	,A.SQL_TEXT
FROM 
	DBA_HIST_SQLTEXT A,
	DBA_HIST_SQLSTAT B
WHERE 
		A.SQL_ID = B.SQL_ID
	AND A.COMMAND_TYPE=3
	AND	A.SQL_TEXT LIKE '%count(1) over (partition by C.INV_COMPANY_TAX_ID,C.PLAN_CODE,C.ACCOUNT_NUMBER,C.SS_NUMBER ) as count_of_participants%' 
GROUP BY 
	 A.SQL_ID
	,B.PARSING_SCHEMA_NAME
--	,A.SQL_TEXT
;






