--break on FILE# skip page
set lin 400 pages 30000 trimspool on colsep ,
col range format a30
col "Av Rd(ms)" format 9999990.99
col "Av Buf Wt(ms)" format 9999990.99
col filename format a60
SELECT 
	A.FILE#
	--A.INSTANCE_NUMBER
    --A.SNAP_ID||'-'||B.SNAP_ID||'-'||A.TSNAME RANGE
	,to_char(C.BEGIN_INTERVAL_TIME,'YYYY-MM-DD HH24:MI') BEGIN_INTERVAL_TIME
	,to_char(C.END_INTERVAL_TIME,'YYYY-MM-DD HH24:MI') END_INTERVAL_TIME
	,A.TSNAME
	--,A.FILENAME
	,B.PHYRDS - A.PHYRDS PHYRDS
	,B.PHYWRTS- A.PHYWRTS PHYWRTS
	--,B.SINGLEBLKRDS - A.SINGLEBLKRDS SINGLEBLKRDS
	,B.READTIM - A.READTIM READTIM
    --,B.WRITETIM - A.WRITETIM WRITETIM
	--,B.SINGLEBLKRDTIM - A.SINGLEBLKRDTIM SINGLEBLKRDTIM
	--,B.PHYBLKRD - A.PHYBLKRD PHYBLKRD
	--,B.PHYBLKWRT - A.PHYBLKWRT PHYBLKWRT
	,B.WAIT_COUNT - A.WAIT_COUNT WAIT_COUNT
	,B.TIME - A.TIME "TIME"
	,nvl((B.READTIM - A.READTIM)/nullif(B.PHYRDS - A.PHYRDS,0),0)*10 "Av Rd(ms)"
	,nvl((B.TIME - A.TIME)/nullif(B.WAIT_COUNT - A.WAIT_COUNT,0),0)*10 "Av Buf Wt(ms)"
FROM
	DBA_HIST_FILESTATXS A, 
	DBA_HIST_FILESTATXS B,
	DBA_HIST_SNAPSHOT C
WHERE 
	    B.SNAP_ID = A.SNAP_ID+1
	AND B.FILE# = A.FILE#
	AND B.INSTANCE_NUMBER = A.INSTANCE_NUMBER
	AND B.SNAP_ID=C.SNAP_ID 
	AND B.INSTANCE_NUMBER = C.INSTANCE_NUMBER
	--AND B.FILE# in (select distinct p1 from bg_ash where sample_time between to_date('2012-11-02 03:38','YYYY-MM-DD HH24:MI') and to_date('2012-11-02 09:28','YYYY-MM-DD HH24:MI') and event='db file sequential read')
	--AND B.TSNAME in ('SYSAUX')
	--AND C.BEGIN_INTERVAL_TIME between to_date('2012-11-15 20:00','YYYY-MM-DD HH24:MI') and to_date('2012-11-16 21:00','YYYY-MM-DD HH24:MI')
	AND C.BEGIN_INTERVAL_TIME>sysdate-5
	--AND nvl((B.READTIM - A.READTIM)/nullif(B.PHYRDS - A.PHYRDS,0),0)*10 >= 10
	--AND B.PHYRDS - A.PHYRDS > 3600
ORDER BY
	A.TSNAME
	,A.FILE#
	,C.BEGIN_INTERVAL_TIME
	--,A.FILE#
;