UNIX

BREAK ON REPORT
COMPUTE SUM OF GB ON REPORT
COL GB FORMAT 999990.99
SELECT 'DATAFILES' AS COMPONENT, SUM(BYTES/1024/1024/1024) AS GB FROM V$DATAFILE
UNION
SELECT 'TEMPFILES', SUM(BYTES/1024/1024/1024) FROM V$TEMPFILE
UNION
SELECT 'LOGFILES', SUM(BYTES/1024/1024/1024) FROM V$LOG A, V$LOGFILE B WHERE A.GROUP#=B.GROUP#
/


-- BY TYPE,PATH
BREAK ON TYPE SKIP PAGE ON PATH SKIP 2 ON REPORT
COMPUTE SUM OF GB ON TYPE
COMPUTE SUM OF GB ON PATH
COMPUTE SUM OF GB ON REPORT
COL GB FORMAT 999990.99
COL TYPE FORMAT A20
COL PATH FORMAT A30
SELECT TYPE, PATH, FILES, GB FROM (
SELECT 'CONTROLFILE' TYPE, SUBSTR(NAME,1,INSTR(NAME,'/',-1)) PATH, COUNT(*) FILES, SUM((BLOCK_SIZE*FILE_SIZE_BLKS)/1024/1024/1024) GB FROM V$CONTROLFILE GROUP BY SUBSTR(NAME,1,INSTR(NAME,'/',-1)) UNION
SELECT 'DATAFILE'    TYPE, SUBSTR(NAME,1,INSTR(NAME,'/',-1)) PATH, COUNT(*) FILES, SUM((BYTES)/1024/1024/1024) GB FROM V$DATAFILE GROUP BY SUBSTR(NAME,1,INSTR(NAME,'/',-1)) UNION
SELECT 'TEMPFILE'    TYPE, SUBSTR(NAME,1,INSTR(NAME,'/',-1)) PATH, COUNT(*) FILES, SUM((BYTES)/1024/1024/1024) GB FROM V$TEMPFILE GROUP BY SUBSTR(NAME,1,INSTR(NAME,'/',-1)) UNION
SELECT 'ONLINEREDO'  TYPE, SUBSTR(LF.MEMBER,1,INSTR(LF.MEMBER,'/',-1)) PATH, COUNT(*) FILES, SUM(L.BYTES/1024/1024/1024) GB FROM V$LOGFILE LF, V$LOG L WHERE LF.GROUP#=L.GROUP# AND LF.TYPE='ONLINE' GROUP BY SUBSTR(LF.MEMBER,1,INSTR(LF.MEMBER,'/',-1))
) ORDER BY TYPE;

-- BY PATH, TYPE
BREAK ON PATH SKIP PAGE ON TYPE SKIP 2 ON REPORT
COMPUTE SUM OF GB ON TYPE
COMPUTE SUM OF GB ON PATH
COL GB FORMAT 999990.99
COL TYPE FORMAT A20
COL PATH FORMAT A30
SELECT PATH, TYPE, FILES, GB FROM (
SELECT 'CONTROLFILE' TYPE, SUBSTR(NAME,1,INSTR(NAME,'/',1)-1) PATH, COUNT(*) FILES, SUM((BLOCK_SIZE*FILE_SIZE_BLKS)/1024/1024/1024) GB FROM V$CONTROLFILE GROUP BY SUBSTR(NAME,1,INSTR(NAME,'/',1)-1) UNION
SELECT 'DATAFILE'    TYPE, SUBSTR(NAME,1,INSTR(NAME,'/',1)-1) PATH, COUNT(*) FILES, SUM((BYTES)/1024/1024/1024) GB FROM V$DATAFILE GROUP BY SUBSTR(NAME,1,INSTR(NAME,'/',1)-1) UNION
SELECT 'TEMPFILE'    TYPE, SUBSTR(NAME,1,INSTR(NAME,'/',1)-1) PATH, COUNT(*) FILES, SUM((BYTES)/1024/1024/1024) GB FROM V$TEMPFILE GROUP BY SUBSTR(NAME,1,INSTR(NAME,'/',1)-1) UNION
SELECT 'ONLINEREDO'  TYPE, SUBSTR(LF.MEMBER,1,INSTR(LF.MEMBER,'/',1)-1) PATH, COUNT(*) FILES, SUM(L.BYTES/1024/1024/1024) GB FROM V$LOGFILE LF, V$LOG L WHERE LF.GROUP#=L.GROUP# AND LF.TYPE='ONLINE' GROUP BY SUBSTR(LF.MEMBER,1,INSTR(LF.MEMBER,'/',1)-1)
) ORDER BY PATH;

SELECT 'CONTROLFILE' TYPE, SUBSTR(NAME,1,INSTR(NAME,'/',1)-1) PATH, COUNT(*) FILES, SUM((BLOCK_SIZE*FILE_SIZE_BLKS)/1024/1024/1024) GB FROM V$CONTROLFILE GROUP BY SUBSTR(NAME,1,INSTR(NAME,'/',1)-1)



-- Windows
SELECT SUBSTR(MEMBER,1,INSTR(MEMBER,'\',-1)) PATH from v$logfile
union
SELECT SUBSTR(name,1,INSTR(name,'\',-1)) PATH from v$datafile
union 
SELECT SUBSTR(name,1,INSTR(name,'\',-1)) PATH from v$tempfile
union
SELECT SUBSTR(name,1,INSTR(name,'\',-1)) PATH from v$controlfile;