SET LIN 4000 PAGES 0 HEAD OFF FEED OFF SERVEROUT ON TRIMSPOOL ON
DECLARE
	V_MYCALL VARCHAR2(4000);
	CURSOR C_JOBS IS SELECT JOB FROM DBA_JOBS WHERE LOG_USER='MVUSER';
BEGIN
	FOR r_job IN c_jobs LOOP
		DBMS_IJOB.FULL_EXPORT (r_job.job, v_mycall);
		DBMS_OUTPUT.PUT_LINE('--------------------');
		DBMS_OUTPUT.PUT_LINE(v_mycall);
	END LOOP;
END;
/
