ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS';

SET LIN 400 PAGES 1000
COL FILE_NAME FORMAT A65
COL TABLESPACE FORMAT A20
COL HANDLE FORMAT A85
COL DATAFILE_MB FORMAT 99999990.99
COL HANDLE_MB FORMAT 99999990.99
BREAK ON RECID SKIP PAGE ON START_TIME SKIP 1 ON COMPLETION_TIME SKIP 1 ON INCREMENTAL_LEVEL SKIP 1 ON HANDLE SKIP 1

PROMPT --DATAFILE BACKUPS
SELECT
	A.RECID,
	A.START_TIME,
	--A.COMPLETION_TIME,
	--A.INCREMENTAL_LEVEL,
	C.HANDLE,
	C.BYTES/1024/1024 HANDLE_MB,
	--C.STATUS,
	--F.NAME TABLESPACE,
	B.FILE#,
	D.NAME FILE_NAME,
	D.BYTES/1024/1024 DATAFILE_MB
	--D.CHECKPOINT_TIME
FROM 
	V$BACKUP_SET A,
	V$BACKUP_DATAFILE B,
	V$BACKUP_PIECE C,
	V$DATAFILE D,
	V$TABLESPACE F
WHERE 
			A.SET_STAMP = B.SET_STAMP
		AND A.SET_COUNT = B.SET_COUNT
		AND A.SET_STAMP = C.SET_STAMP
		AND A.SET_COUNT = C.SET_COUNT
		AND B.FILE# = D.FILE#
		AND D.TS# = F.TS#
		AND C.STATUS = 'A'
		AND B.FILE# != 0  -- THIS IS THE CONTROLFILE
ORDER BY 
	A.RECID,
	F.NAME
;


SELECT
	 A.RECID
	,A.START_TIME
	,A.COMPLETION_TIME
	,C.HANDLE
	,B.THREAD#
	,B.SEQUENCE#
	,B.FIRST_TIME
	,B.NEXT_TIME
FROM
	V$BACKUP_SET A,
	V$BACKUP_REDOLOG B,
	V$BACKUP_PIECE C
WHERE
			A.SET_STAMP = B.SET_STAMP
		AND A.SET_COUNT = B.SET_COUNT
		AND A.SET_STAMP = C.SET_STAMP
		AND A.SET_COUNT = C.SET_COUNT
		AND C.STATUS = 'A'
		AND A.COMPLETION_TIME > SYSDATE - 1
ORDER BY 
	 A.RECID
	,B.THREAD#
	,B.SEQUENCE#
;
	


