ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS';
BREAK ON OPNAME SKIP PAGE
SET LIN 400 PAGES 200
COL OPNAME FORMAT A35
COL "SID,SERIAL" FORMAT A15
COL MESSAGE FORMAT A45 TRUNC
COL ACTION FORMAT A25 TRUNC
COL MIN_ELAPSED FORMAT 99990.99
COL MIN_REMAINING FORMAT 99990.99
COL MIN_TOTAL FORMAT 99990.99
COL PCT_COMPLETE FORMAT 99990.99
COL ETC FORMAT A25
SELECT 
	B.OPNAME,
	A.SID||','||A.SERIAL# "SID,SERIAL",
	A.ACTION,
	substr(message,instr(message,':',-1)+2) MESSAGE,
	B.TIME_REMAINING/60 MIN_REMAINING,
	B.ELAPSED_SECONDS/60 MIN_ELAPSED,
    (B.ELAPSED_SECONDS+B.TIME_REMAINING)/60 MIN_TOTAL,
	(B.SOFAR/B.TOTALWORK)*100 PCT_COMPLETE,
	to_char(SYSDATE+(B.TIME_REMAINING/86400),'YYYY-MM-DD HH24:MI:SS') ETC
FROM 
	V$SESSION A,
	V$SESSION_LONGOPS B
WHERE 
	A.SID = B.SID AND 
	UPPER(A.PROGRAM) LIKE 'RMAN%'
	AND SOFAR < TOTALWORK 
ORDER BY 
	OPNAME, PCT_COMPLETE
;
